


var input = [
    { outerBag: "faded yellow", innerBags: [{ number: 4, color: "mirrored fuchsia"}, { number: 4, color: "dotted indigo"}, { number: 3, color: "faded orange"}, { number: 5, color: "plaid crimson"}] },
    { outerBag: "striped olive", innerBags: [{ number: 4, color: "dark crimson"}] },
    { outerBag: "dotted indigo", innerBags: [{ number: 4, color: "faded black"}, { number: 4, color: "clear cyan"}, { number: 5, color: "vibrant teal"}] },
    { outerBag: "plaid crimson", innerBags: [{ number: 3, color: "shiny gold"}, { number: 3, color: "plaid gray"}] },
    { outerBag: "muted fuchsia", innerBags: [{ number: 3, color: "shiny bronze"}] },
    { outerBag: "plaid gray", innerBags: [] },
    { outerBag: "dull maroon", innerBags: [{ number: 2, color: "posh maroon"}, { number: 3, color: "wavy aqua"}, { number: 2, color: "faded white"}, { number: 5, color: "posh bronze"}] },
    { outerBag: "dull red", innerBags: [{ number: 3, color: "striped silver"}, { number: 2, color: "dark tan"}] },
    { outerBag: "muted lavender", innerBags: [{ number: 3, color: "striped red"}] },
    { outerBag: "shiny lime", innerBags: [{ number: 1, color: "dotted olive"}] },
    { outerBag: "dim violet", innerBags: [{ number: 5, color: "faded orange"}, { number: 4, color: "plaid green"}, { number: 1, color: "faded black"}] },
    { outerBag: "wavy indigo", innerBags: [{ number: 4, color: "bright aqua"}, { number: 2, color: "dotted orange"}, { number: 2, color: "vibrant yellow"}] },
    { outerBag: "vibrant purple", innerBags: [{ number: 3, color: "plaid indigo"}, { number: 3, color: "dark gold"}, { number: 3, color: "striped yellow"}, { number: 3, color: "light tomato"}] },
    { outerBag: "plaid plum", innerBags: [{ number: 1, color: "faded silver"}] },
    { outerBag: "striped teal", innerBags: [{ number: 2, color: "shiny crimson"}, { number: 1, color: "dull gray"}, { number: 3, color: "vibrant teal"}] },
    { outerBag: "posh crimson", innerBags: [{ number: 2, color: "light violet"}] },
    { outerBag: "pale maroon", innerBags: [{ number: 2, color: "wavy maroon"}, { number: 1, color: "dotted white"}] },
    { outerBag: "drab cyan", innerBags: [{ number: 4, color: "dim violet"}, { number: 5, color: "pale tan"}, { number: 3, color: "faded black"}] },
    { outerBag: "bright black", innerBags: [{ number: 2, color: "faded magenta"}] },
    { outerBag: "dotted green", innerBags: [{ number: 3, color: "muted cyan"}] },
    { outerBag: "striped chartreuse", innerBags: [{ number: 5, color: "posh silver"}, { number: 5, color: "wavy violet"}] },
    { outerBag: "drab olive", innerBags: [{ number: 5, color: "dull blue"}] },
    { outerBag: "drab green", innerBags: [{ number: 2, color: "vibrant violet"}, { number: 2, color: "dim violet"}, { number: 2, color: "light brown"}] },
    { outerBag: "dark violet", innerBags: [{ number: 5, color: "drab brown"}, { number: 4, color: "dim chartreuse"}, { number: 4, color: "dark salmon"}] },
    { outerBag: "faded orange", innerBags: [{ number: 4, color: "dull lavender"}] },
    { outerBag: "dark fuchsia", innerBags: [{ number: 2, color: "clear tomato"}] },
    { outerBag: "plaid gold", innerBags: [{ number: 3, color: "clear tomato"}] },
    { outerBag: "muted red", innerBags: [{ number: 1, color: "muted green"}] },
    { outerBag: "dark coral", innerBags: [{ number: 5, color: "muted white"}, { number: 3, color: "mirrored indigo"}, { number: 1, color: "shiny blue"}, { number: 2, color: "drab green"}] },
    { outerBag: "dark chartreuse", innerBags: [{ number: 2, color: "bright teal"}] },
    { outerBag: "dim silver", innerBags: [{ number: 4, color: "shiny white"}, { number: 2, color: "vibrant plum"}, { number: 3, color: "clear plum"}] },
    { outerBag: "clear silver", innerBags: [{ number: 1, color: "dull gray"}] },
    { outerBag: "pale gray", innerBags: [] },
    { outerBag: "plaid chartreuse", innerBags: [{ number: 3, color: "dull brown"}] },
    { outerBag: "dotted crimson", innerBags: [{ number: 3, color: "pale olive"}, { number: 2, color: "pale black"}] },
    { outerBag: "dark blue", innerBags: [{ number: 1, color: "light red"}, { number: 5, color: "striped turquoise"}] },
    { outerBag: "dim white", innerBags: [{ number: 5, color: "bright white"}, { number: 4, color: "light magenta"}, { number: 4, color: "wavy chartreuse"}] },
    { outerBag: "striped magenta", innerBags: [{ number: 3, color: "dull coral"}] },
    { outerBag: "drab bronze", innerBags: [{ number: 4, color: "bright red"}] },
    { outerBag: "light gray", innerBags: [{ number: 1, color: "mirrored coral"}] },
    { outerBag: "wavy brown", innerBags: [{ number: 4, color: "clear lime"}, { number: 1, color: "plaid lavender"}, { number: 1, color: "faded lavender"}] },
    { outerBag: "bright violet", innerBags: [{ number: 5, color: "clear indigo"}, { number: 1, color: "plaid indigo"}, { number: 3, color: "light beige"}] },
    { outerBag: "drab tan", innerBags: [{ number: 4, color: "drab chartreuse"}] },
    { outerBag: "shiny teal", innerBags: [{ number: 1, color: "bright tan"}] },
    { outerBag: "dark silver", innerBags: [{ number: 1, color: "drab orange"}, { number: 1, color: "striped plum"}, { number: 2, color: "bright gold"}] },
    { outerBag: "wavy turquoise", innerBags: [{ number: 3, color: "striped gray"}, { number: 1, color: "dotted lime"}, { number: 4, color: "pale plum"}, { number: 2, color: "vibrant orange"}] },
    { outerBag: "wavy red", innerBags: [{ number: 1, color: "dim gold"}, { number: 1, color: "striped turquoise"}, { number: 1, color: "bright red"}] },
    { outerBag: "mirrored yellow", innerBags: [{ number: 5, color: "faded cyan"}, { number: 2, color: "wavy green"}] },
    { outerBag: "wavy blue", innerBags: [{ number: 5, color: "dark violet"}, { number: 4, color: "vibrant gray"}] },
    { outerBag: "mirrored olive", innerBags: [{ number: 5, color: "faded orange"}, { number: 2, color: "posh aqua"}, { number: 3, color: "dotted silver"}, { number: 2, color: "striped plum"}] },
    { outerBag: "faded crimson", innerBags: [{ number: 3, color: "striped maroon"}, { number: 4, color: "pale tomato"}] },
    { outerBag: "vibrant olive", innerBags: [{ number: 2, color: "wavy yellow"}, { number: 2, color: "mirrored orange"}] },
    { outerBag: "vibrant fuchsia", innerBags: [{ number: 4, color: "dim yellow"}, { number: 3, color: "drab tan"}] },
    { outerBag: "dotted tan", innerBags: [{ number: 2, color: "faded fuchsia"}, { number: 2, color: "pale turquoise"}, { number: 4, color: "mirrored gray"}] },
    { outerBag: "mirrored beige", innerBags: [{ number: 1, color: "mirrored olive"}] },
    { outerBag: "faded turquoise", innerBags: [{ number: 5, color: "dull yellow"}, { number: 5, color: "clear gray"}, { number: 5, color: "muted lavender"}] },
    { outerBag: "wavy violet", innerBags: [{ number: 5, color: "dotted gold"}, { number: 5, color: "dull cyan"}] },
    { outerBag: "light tan", innerBags: [{ number: 1, color: "dull salmon"}, { number: 1, color: "dull bronze"}, { number: 1, color: "dull tan"}] },
    { outerBag: "wavy tan", innerBags: [{ number: 4, color: "drab black"}] },
    { outerBag: "muted silver", innerBags: [{ number: 1, color: "dark lavender"}, { number: 5, color: "pale tan"}, { number: 2, color: "clear violet"}, { number: 3, color: "drab coral"}] },
    { outerBag: "dull blue", innerBags: [{ number: 5, color: "muted olive"}, { number: 2, color: "drab salmon"}, { number: 3, color: "clear red"}] },
    { outerBag: "bright chartreuse", innerBags: [{ number: 5, color: "dim teal"}] },
    { outerBag: "posh bronze", innerBags: [{ number: 3, color: "plaid black"}, { number: 1, color: "clear lavender"}, { number: 3, color: "dim chartreuse"}, { number: 1, color: "plaid gray"}] },
    { outerBag: "striped orange", innerBags: [{ number: 5, color: "dull turquoise"}, { number: 2, color: "dotted olive"}, { number: 5, color: "bright coral"}, { number: 1, color: "mirrored aqua"}] },
    { outerBag: "posh white", innerBags: [{ number: 4, color: "dim tomato"}, { number: 5, color: "light salmon"}] },
    { outerBag: "faded cyan", innerBags: [{ number: 2, color: "plaid crimson"}, { number: 5, color: "muted green"}, { number: 4, color: "bright olive"}] },
    { outerBag: "dark red", innerBags: [{ number: 2, color: "bright blue"}, { number: 5, color: "faded turquoise"}, { number: 5, color: "bright black"}] },
    { outerBag: "pale magenta", innerBags: [{ number: 4, color: "drab chartreuse"}, { number: 2, color: "light tomato"}, { number: 5, color: "dull lavender"}] },
    { outerBag: "posh orange", innerBags: [{ number: 3, color: "muted gray"}] },
    { outerBag: "clear tan", innerBags: [{ number: 2, color: "dim crimson"}, { number: 3, color: "light olive"}] },
    { outerBag: "dark green", innerBags: [{ number: 4, color: "muted maroon"}, { number: 5, color: "striped gold"}, { number: 2, color: "drab indigo"}, { number: 2, color: "dotted silver"}] },
    { outerBag: "dim blue", innerBags: [{ number: 5, color: "wavy coral"}, { number: 4, color: "shiny chartreuse"}, { number: 5, color: "bright teal"}, { number: 2, color: "drab beige"}] },
    { outerBag: "dim indigo", innerBags: [{ number: 2, color: "dull cyan"}, { number: 3, color: "dark maroon"}] },
    { outerBag: "dotted gold", innerBags: [{ number: 4, color: "drab tomato"}, { number: 1, color: "light cyan"}, { number: 2, color: "pale tan"}, { number: 2, color: "light tomato"}] },
    { outerBag: "faded gold", innerBags: [{ number: 2, color: "drab tan"}, { number: 5, color: "mirrored chartreuse"}, { number: 2, color: "striped gold"}, { number: 3, color: "bright silver"}] },
    { outerBag: "muted olive", innerBags: [{ number: 2, color: "plaid black"}, { number: 3, color: "shiny gold"}, { number: 4, color: "vibrant crimson"}] },
    { outerBag: "shiny gray", innerBags: [{ number: 4, color: "clear violet"}] },
    { outerBag: "dim teal", innerBags: [] },
    { outerBag: "drab fuchsia", innerBags: [{ number: 4, color: "dim purple"}, { number: 4, color: "striped beige"}] },
    { outerBag: "dark cyan", innerBags: [{ number: 3, color: "drab salmon"}] },
    { outerBag: "clear lavender", innerBags: [{ number: 2, color: "dim olive"}, { number: 4, color: "mirrored gold"}, { number: 4, color: "striped plum"}] },
    { outerBag: "posh lime", innerBags: [{ number: 4, color: "mirrored teal"}, { number: 3, color: "wavy chartreuse"}, { number: 2, color: "pale cyan"}, { number: 5, color: "pale indigo"}] },
    { outerBag: "vibrant gold", innerBags: [{ number: 5, color: "dim chartreuse"}, { number: 1, color: "mirrored red"}, { number: 3, color: "dark lime"}, { number: 4, color: "shiny silver"}] },
    { outerBag: "light crimson", innerBags: [{ number: 3, color: "muted lavender"}] },
    { outerBag: "dark lime", innerBags: [{ number: 1, color: "faded chartreuse"}, { number: 3, color: "shiny crimson"}, { number: 2, color: "drab aqua"}] },
    { outerBag: "dotted beige", innerBags: [{ number: 1, color: "faded white"}, { number: 5, color: "vibrant yellow"}] },
    { outerBag: "dim chartreuse", innerBags: [{ number: 4, color: "striped lime"}, { number: 2, color: "faded black"}] },
    { outerBag: "wavy bronze", innerBags: [{ number: 5, color: "muted cyan"}, { number: 3, color: "light yellow"}, { number: 4, color: "dotted purple"}] },
    { outerBag: "striped plum", innerBags: [{ number: 2, color: "drab black"}, { number: 1, color: "faded silver"}] },
    { outerBag: "posh chartreuse", innerBags: [{ number: 4, color: "faded blue"}, { number: 2, color: "vibrant crimson"}, { number: 4, color: "dotted purple"}, { number: 4, color: "posh tan"}] },
    { outerBag: "vibrant yellow", innerBags: [{ number: 4, color: "dim tan"}, { number: 1, color: "mirrored fuchsia"}] },
    { outerBag: "pale salmon", innerBags: [{ number: 2, color: "dull tan"}, { number: 2, color: "mirrored crimson"}, { number: 1, color: "drab chartreuse"}, { number: 3, color: "muted crimson"}] },
    { outerBag: "drab gray", innerBags: [{ number: 2, color: "vibrant coral"}] },
    { outerBag: "mirrored teal", innerBags: [{ number: 5, color: "vibrant violet"}] },
    { outerBag: "striped maroon", innerBags: [{ number: 2, color: "dim violet"}, { number: 3, color: "dotted gold"}, { number: 4, color: "bright olive"}] },
    { outerBag: "clear turquoise", innerBags: [{ number: 4, color: "plaid green"}] },
    { outerBag: "vibrant white", innerBags: [{ number: 5, color: "dotted beige"}] },
    { outerBag: "wavy chartreuse", innerBags: [{ number: 1, color: "faded orange"}, { number: 4, color: "shiny lavender"}] },
    { outerBag: "mirrored gray", innerBags: [{ number: 1, color: "clear magenta"}] },
    { outerBag: "bright aqua", innerBags: [{ number: 3, color: "mirrored gold"}, { number: 5, color: "shiny magenta"}, { number: 1, color: "shiny silver"}, { number: 5, color: "posh tan"}] },
    { outerBag: "plaid violet", innerBags: [{ number: 2, color: "muted olive"}, { number: 2, color: "dotted chartreuse"}, { number: 2, color: "faded magenta"}, { number: 1, color: "drab cyan"}] },
    { outerBag: "plaid olive", innerBags: [{ number: 3, color: "wavy lime"}, { number: 2, color: "faded cyan"}, { number: 2, color: "posh tan"}] },
    { outerBag: "bright crimson", innerBags: [{ number: 4, color: "clear beige"}, { number: 1, color: "plaid teal"}, { number: 3, color: "shiny magenta"}] },
    { outerBag: "shiny salmon", innerBags: [{ number: 3, color: "light silver"}, { number: 3, color: "faded orange"}, { number: 3, color: "dim tomato"}, { number: 3, color: "shiny gold"}] },
    { outerBag: "mirrored red", innerBags: [{ number: 5, color: "shiny black"}] },
    { outerBag: "shiny fuchsia", innerBags: [{ number: 1, color: "faded yellow"}, { number: 1, color: "plaid teal"}] },
    { outerBag: "wavy tomato", innerBags: [{ number: 4, color: "light crimson"}, { number: 3, color: "clear blue"}] },
    { outerBag: "clear lime", innerBags: [{ number: 4, color: "dark gray"}, { number: 5, color: "drab tomato"}] },
    { outerBag: "light maroon", innerBags: [{ number: 3, color: "dark plum"}, { number: 4, color: "plaid crimson"}] },
    { outerBag: "drab yellow", innerBags: [{ number: 3, color: "vibrant aqua"}, { number: 5, color: "pale red"}] },
    { outerBag: "mirrored fuchsia", innerBags: [{ number: 3, color: "pale purple"}, { number: 1, color: "clear yellow"}, { number: 1, color: "wavy black"}, { number: 4, color: "pale gray"}] },
    { outerBag: "clear black", innerBags: [{ number: 1, color: "plaid lavender"}, { number: 4, color: "muted indigo"}] },
    { outerBag: "drab silver", innerBags: [{ number: 1, color: "faded green"}, { number: 3, color: "pale black"}] },
    { outerBag: "clear teal", innerBags: [{ number: 2, color: "dotted silver"}] },
    { outerBag: "plaid indigo", innerBags: [{ number: 4, color: "dotted purple"}] },
    { outerBag: "striped indigo", innerBags: [{ number: 1, color: "mirrored indigo"}, { number: 4, color: "faded plum"}, { number: 4, color: "wavy crimson"}] },
    { outerBag: "light salmon", innerBags: [] },
    { outerBag: "dull plum", innerBags: [{ number: 4, color: "plaid cyan"}] },
    { outerBag: "muted tomato", innerBags: [{ number: 4, color: "dark violet"}] },
    { outerBag: "mirrored orange", innerBags: [] },
    { outerBag: "striped tomato", innerBags: [{ number: 5, color: "dotted chartreuse"}, { number: 2, color: "dark white"}] },
    { outerBag: "dotted magenta", innerBags: [{ number: 2, color: "wavy gold"}, { number: 5, color: "pale gray"}, { number: 2, color: "bright chartreuse"}] },
    { outerBag: "vibrant blue", innerBags: [{ number: 3, color: "dotted cyan"}, { number: 4, color: "clear gold"}, { number: 2, color: "dark cyan"}] },
    { outerBag: "mirrored crimson", innerBags: [{ number: 1, color: "dim salmon"}, { number: 4, color: "posh aqua"}] },
    { outerBag: "shiny turquoise", innerBags: [{ number: 2, color: "striped blue"}, { number: 2, color: "light orange"}, { number: 3, color: "dim fuchsia"}, { number: 2, color: "dark olive"}] },
    { outerBag: "muted gray", innerBags: [{ number: 3, color: "dotted yellow"}, { number: 4, color: "dim orange"}, { number: 3, color: "clear beige"}, { number: 3, color: "posh tan"}] },
    { outerBag: "dim bronze", innerBags: [{ number: 1, color: "light magenta"}, { number: 4, color: "shiny purple"}, { number: 1, color: "light red"}] },
    { outerBag: "dotted olive", innerBags: [{ number: 2, color: "dark crimson"}] },
    { outerBag: "plaid bronze", innerBags: [{ number: 4, color: "bright silver"}, { number: 1, color: "faded lime"}, { number: 3, color: "striped lime"}, { number: 3, color: "drab coral"}] },
    { outerBag: "posh blue", innerBags: [{ number: 2, color: "clear tomato"}] },
    { outerBag: "plaid coral", innerBags: [{ number: 4, color: "clear turquoise"}, { number: 1, color: "plaid brown"}, { number: 1, color: "drab indigo"}] },
    { outerBag: "faded magenta", innerBags: [{ number: 2, color: "wavy gray"}, { number: 4, color: "dark gold"}, { number: 4, color: "shiny white"}, { number: 4, color: "faded black"}] },
    { outerBag: "light brown", innerBags: [{ number: 3, color: "striped red"}, { number: 4, color: "faded black"}, { number: 5, color: "vibrant violet"}] },
    { outerBag: "dotted turquoise", innerBags: [{ number: 2, color: "mirrored orange"}] },
    { outerBag: "pale bronze", innerBags: [{ number: 2, color: "mirrored silver"}, { number: 1, color: "faded cyan"}] },
    { outerBag: "dark purple", innerBags: [{ number: 1, color: "muted lavender"}, { number: 1, color: "dull yellow"}, { number: 5, color: "vibrant tan"}, { number: 1, color: "dark gold"}] },
    { outerBag: "plaid white", innerBags: [{ number: 2, color: "pale turquoise"}, { number: 4, color: "clear green"}] },
    { outerBag: "wavy magenta", innerBags: [{ number: 3, color: "shiny blue"}, { number: 1, color: "dark yellow"}] },
    { outerBag: "wavy gold", innerBags: [{ number: 1, color: "dotted indigo"}] },
    { outerBag: "dull lavender", innerBags: [{ number: 1, color: "striped plum"}, { number: 5, color: "pale gray"}] },
    { outerBag: "shiny silver", innerBags: [{ number: 5, color: "shiny lavender"}, { number: 1, color: "plaid crimson"}, { number: 1, color: "wavy black"}] },
    { outerBag: "clear blue", innerBags: [{ number: 2, color: "plaid bronze"}, { number: 1, color: "shiny purple"}] },
    { outerBag: "faded chartreuse", innerBags: [{ number: 3, color: "dull bronze"}] },
    { outerBag: "pale blue", innerBags: [{ number: 3, color: "plaid yellow"}, { number: 1, color: "pale black"}, { number: 4, color: "clear magenta"}, { number: 3, color: "mirrored silver"}] },
    { outerBag: "vibrant green", innerBags: [{ number: 4, color: "bright magenta"}, { number: 4, color: "dark black"}, { number: 5, color: "wavy chartreuse"}] },
    { outerBag: "drab tomato", innerBags: [{ number: 3, color: "drab orange"}, { number: 4, color: "striped coral"}] },
    { outerBag: "clear cyan", innerBags: [{ number: 3, color: "wavy chartreuse"}, { number: 1, color: "light salmon"}, { number: 2, color: "dim purple"}] },
    { outerBag: "dim magenta", innerBags: [{ number: 4, color: "dim turquoise"}, { number: 1, color: "clear gray"}, { number: 4, color: "dim lime"}, { number: 3, color: "mirrored tomato"}] },
    { outerBag: "wavy maroon", innerBags: [{ number: 5, color: "pale plum"}, { number: 3, color: "pale black"}, { number: 3, color: "striped red"}, { number: 4, color: "drab salmon"}] },
    { outerBag: "posh gold", innerBags: [{ number: 3, color: "dim chartreuse"}, { number: 1, color: "faded blue"}, { number: 4, color: "mirrored teal"}] },
    { outerBag: "muted aqua", innerBags: [{ number: 2, color: "faded maroon"}, { number: 1, color: "mirrored blue"}, { number: 5, color: "pale crimson"}] },
    { outerBag: "muted orange", innerBags: [{ number: 1, color: "muted olive"}] },
    { outerBag: "posh tan", innerBags: [{ number: 4, color: "muted lavender"}, { number: 2, color: "plaid crimson"}, { number: 4, color: "striped lime"}] },
    { outerBag: "mirrored indigo", innerBags: [{ number: 1, color: "muted olive"}, { number: 2, color: "vibrant chartreuse"}, { number: 4, color: "light cyan"}] },
    { outerBag: "wavy crimson", innerBags: [{ number: 4, color: "mirrored violet"}, { number: 2, color: "vibrant olive"}, { number: 5, color: "dull lavender"}, { number: 1, color: "drab cyan"}] },
    { outerBag: "dim lavender", innerBags: [{ number: 4, color: "light salmon"}, { number: 5, color: "plaid tomato"}, { number: 4, color: "drab fuchsia"}] },
    { outerBag: "dotted yellow", innerBags: [{ number: 4, color: "vibrant chartreuse"}] },
    { outerBag: "light fuchsia", innerBags: [{ number: 2, color: "wavy red"}, { number: 2, color: "faded lime"}, { number: 1, color: "pale brown"}, { number: 5, color: "dotted green"}] },
    { outerBag: "clear beige", innerBags: [{ number: 5, color: "drab chartreuse"}, { number: 4, color: "dark olive"}, { number: 5, color: "dim gold"}] },
    { outerBag: "shiny gold", innerBags: [{ number: 1, color: "pale turquoise"}] },
    { outerBag: "dim tomato", innerBags: [] },
    { outerBag: "plaid salmon", innerBags: [{ number: 1, color: "striped tan"}, { number: 5, color: "plaid purple"}, { number: 1, color: "mirrored crimson"}] },
    { outerBag: "dotted lavender", innerBags: [{ number: 3, color: "striped teal"}, { number: 1, color: "vibrant gray"}] },
    { outerBag: "light olive", innerBags: [{ number: 3, color: "posh tomato"}, { number: 5, color: "dim coral"}, { number: 4, color: "posh white"}, { number: 2, color: "dark turquoise"}] },
    { outerBag: "striped silver", innerBags: [{ number: 1, color: "clear tomato"}, { number: 1, color: "drab cyan"}] },
    { outerBag: "striped lavender", innerBags: [{ number: 4, color: "posh chartreuse"}, { number: 5, color: "faded coral"}] },
    { outerBag: "faded beige", innerBags: [{ number: 5, color: "muted gold"}, { number: 5, color: "clear gold"}, { number: 2, color: "posh white"}] },
    { outerBag: "drab indigo", innerBags: [{ number: 1, color: "pale magenta"}] },
    { outerBag: "light blue", innerBags: [{ number: 2, color: "light chartreuse"}, { number: 4, color: "drab black"}, { number: 2, color: "dull bronze"}] },
    { outerBag: "dull gold", innerBags: [{ number: 5, color: "dark blue"}, { number: 2, color: "bright green"}] },
    { outerBag: "faded bronze", innerBags: [{ number: 5, color: "dim olive"}] },
    { outerBag: "mirrored lime", innerBags: [{ number: 5, color: "pale crimson"}] },
    { outerBag: "shiny coral", innerBags: [{ number: 3, color: "drab green"}, { number: 3, color: "posh white"}, { number: 4, color: "clear gray"}, { number: 3, color: "muted orange"}] },
    { outerBag: "clear magenta", innerBags: [{ number: 3, color: "plaid olive"}, { number: 4, color: "plaid indigo"}, { number: 1, color: "dull blue"}] },
    { outerBag: "wavy black", innerBags: [{ number: 3, color: "clear cyan"}, { number: 3, color: "dull bronze"}, { number: 2, color: "wavy chartreuse"}] },
    { outerBag: "pale green", innerBags: [{ number: 2, color: "mirrored silver"}, { number: 3, color: "drab blue"}, { number: 5, color: "drab green"}, { number: 4, color: "pale tomato"}] },
    { outerBag: "drab violet", innerBags: [{ number: 1, color: "drab orange"}, { number: 1, color: "vibrant indigo"}, { number: 2, color: "mirrored chartreuse"}] },
    { outerBag: "light chartreuse", innerBags: [{ number: 4, color: "posh white"}, { number: 5, color: "dull bronze"}, { number: 4, color: "wavy coral"}] },
    { outerBag: "dull black", innerBags: [{ number: 4, color: "muted red"}, { number: 4, color: "faded white"}, { number: 5, color: "plaid tomato"}, { number: 2, color: "dark blue"}] },
    { outerBag: "dark gray", innerBags: [{ number: 2, color: "bright green"}, { number: 5, color: "light blue"}, { number: 3, color: "light tan"}, { number: 2, color: "shiny gold"}] },
    { outerBag: "light turquoise", innerBags: [{ number: 5, color: "shiny coral"}, { number: 3, color: "dull brown"}, { number: 3, color: "striped tan"}, { number: 4, color: "striped silver"}] },
    { outerBag: "mirrored magenta", innerBags: [{ number: 3, color: "vibrant silver"}, { number: 4, color: "vibrant crimson"}, { number: 4, color: "shiny coral"}, { number: 1, color: "shiny indigo"}] },
    { outerBag: "dull lime", innerBags: [{ number: 3, color: "pale turquoise"}, { number: 2, color: "bright olive"}] },
    { outerBag: "mirrored gold", innerBags: [{ number: 1, color: "faded silver"}, { number: 4, color: "pale gray"}] },
    { outerBag: "clear chartreuse", innerBags: [{ number: 4, color: "dark gray"}, { number: 1, color: "pale lime"}, { number: 1, color: "plaid fuchsia"}] },
    { outerBag: "dull indigo", innerBags: [{ number: 4, color: "posh silver"}] },
    { outerBag: "dull yellow", innerBags: [{ number: 3, color: "wavy lavender"}, { number: 3, color: "muted maroon"}] },
    { outerBag: "bright silver", innerBags: [{ number: 2, color: "wavy black"}, { number: 1, color: "dim coral"}] },
    { outerBag: "clear indigo", innerBags: [{ number: 1, color: "posh black"}, { number: 4, color: "muted teal"}, { number: 1, color: "wavy maroon"}] },
    { outerBag: "bright brown", innerBags: [{ number: 3, color: "shiny cyan"}, { number: 5, color: "clear green"}, { number: 1, color: "wavy magenta"}] },
    { outerBag: "shiny crimson", innerBags: [{ number: 1, color: "faded black"}, { number: 2, color: "vibrant chartreuse"}] },
    { outerBag: "striped white", innerBags: [{ number: 4, color: "light red"}, { number: 3, color: "dotted cyan"}] },
    { outerBag: "pale tomato", innerBags: [{ number: 1, color: "posh white"}] },
    { outerBag: "posh salmon", innerBags: [{ number: 2, color: "striped white"}, { number: 5, color: "clear purple"}, { number: 5, color: "bright yellow"}] },
    { outerBag: "faded blue", innerBags: [{ number: 5, color: "drab cyan"}, { number: 1, color: "plaid crimson"}, { number: 5, color: "light crimson"}] },
    { outerBag: "mirrored black", innerBags: [{ number: 4, color: "light tan"}, { number: 3, color: "faded blue"}] },
    { outerBag: "bright red", innerBags: [{ number: 3, color: "pale magenta"}, { number: 4, color: "faded chartreuse"}] },
    { outerBag: "drab lavender", innerBags: [{ number: 5, color: "dim red"}, { number: 4, color: "wavy black"}, { number: 4, color: "dull cyan"}, { number: 5, color: "clear gray"}] },
    { outerBag: "light coral", innerBags: [{ number: 4, color: "dark lavender"}, { number: 2, color: "clear orange"}, { number: 2, color: "dull maroon"}] },
    { outerBag: "bright plum", innerBags: [{ number: 1, color: "shiny blue"}, { number: 5, color: "striped salmon"}, { number: 2, color: "plaid olive"}] },
    { outerBag: "faded tomato", innerBags: [{ number: 4, color: "pale turquoise"}] },
    { outerBag: "wavy purple", innerBags: [{ number: 1, color: "light red"}] },
    { outerBag: "striped crimson", innerBags: [{ number: 2, color: "shiny tan"}, { number: 1, color: "striped salmon"}, { number: 5, color: "dotted cyan"}] },
    { outerBag: "posh olive", innerBags: [{ number: 3, color: "vibrant indigo"}] },
    { outerBag: "plaid red", innerBags: [{ number: 4, color: "dotted violet"}, { number: 1, color: "plaid black"}, { number: 4, color: "light chartreuse"}] },
    { outerBag: "pale aqua", innerBags: [{ number: 3, color: "plaid brown"}] },
    { outerBag: "dotted silver", innerBags: [{ number: 5, color: "striped plum"}] },
    { outerBag: "plaid magenta", innerBags: [{ number: 4, color: "clear lime"}, { number: 1, color: "muted chartreuse"}, { number: 1, color: "dark gray"}] },
    { outerBag: "vibrant plum", innerBags: [{ number: 3, color: "clear yellow"}, { number: 1, color: "striped salmon"}] },
    { outerBag: "faded lime", innerBags: [{ number: 5, color: "dull plum"}] },
    { outerBag: "wavy lavender", innerBags: [{ number: 3, color: "dull bronze"}] },
    { outerBag: "clear olive", innerBags: [{ number: 5, color: "pale bronze"}] },
    { outerBag: "striped cyan", innerBags: [{ number: 2, color: "dotted gray"}] },
    { outerBag: "drab black", innerBags: [] },
    { outerBag: "posh turquoise", innerBags: [{ number: 1, color: "clear teal"}] },
    { outerBag: "plaid lime", innerBags: [{ number: 5, color: "pale gray"}, { number: 5, color: "shiny black"}, { number: 2, color: "faded tan"}, { number: 4, color: "clear lavender"}] },
    { outerBag: "drab maroon", innerBags: [{ number: 4, color: "posh maroon"}, { number: 3, color: "drab lavender"}, { number: 2, color: "shiny lavender"}] },
    { outerBag: "dull beige", innerBags: [{ number: 3, color: "mirrored coral"}, { number: 2, color: "faded fuchsia"}, { number: 5, color: "bright fuchsia"}] },
    { outerBag: "dull bronze", innerBags: [{ number: 2, color: "mirrored olive"}] },
    { outerBag: "striped violet", innerBags: [{ number: 2, color: "vibrant orange"}, { number: 3, color: "muted indigo"}, { number: 5, color: "light plum"}, { number: 2, color: "dark lavender"}] },
    { outerBag: "striped fuchsia", innerBags: [{ number: 3, color: "striped salmon"}, { number: 4, color: "posh brown"}, { number: 1, color: "posh maroon"}] },
    { outerBag: "light aqua", innerBags: [{ number: 4, color: "clear plum"}, { number: 1, color: "dull orange"}, { number: 5, color: "wavy magenta"}, { number: 5, color: "pale chartreuse"}] },
    { outerBag: "wavy lime", innerBags: [{ number: 1, color: "mirrored teal"}, { number: 1, color: "posh tan"}, { number: 5, color: "clear teal"}, { number: 4, color: "plaid crimson"}] },
    { outerBag: "plaid fuchsia", innerBags: [{ number: 4, color: "dark gold"}, { number: 1, color: "muted red"}, { number: 4, color: "light tomato"}] },
    { outerBag: "muted white", innerBags: [{ number: 5, color: "plaid brown"}, { number: 4, color: "dotted plum"}, { number: 3, color: "dim crimson"}, { number: 3, color: "dim aqua"}] },
    { outerBag: "pale white", innerBags: [{ number: 4, color: "mirrored chartreuse"}, { number: 2, color: "bright lavender"}, { number: 5, color: "striped teal"}] },
    { outerBag: "vibrant aqua", innerBags: [{ number: 3, color: "faded green"}, { number: 4, color: "muted tomato"}, { number: 2, color: "clear lavender"}] },
    { outerBag: "posh red", innerBags: [{ number: 4, color: "bright chartreuse"}, { number: 1, color: "clear red"}] },
    { outerBag: "striped yellow", innerBags: [{ number: 2, color: "faded aqua"}, { number: 3, color: "light fuchsia"}, { number: 5, color: "dotted purple"}, { number: 5, color: "drab coral"}] },
    { outerBag: "shiny lavender", innerBags: [{ number: 2, color: "faded orange"}] },
    { outerBag: "dull coral", innerBags: [{ number: 1, color: "dull tan"}, { number: 2, color: "dull beige"}, { number: 3, color: "faded maroon"}, { number: 1, color: "wavy aqua"}] },
    { outerBag: "faded violet", innerBags: [{ number: 5, color: "clear red"}] },
    { outerBag: "dark turquoise", innerBags: [{ number: 3, color: "light chartreuse"}] },
    { outerBag: "plaid silver", innerBags: [{ number: 2, color: "drab cyan"}, { number: 1, color: "dotted gray"}, { number: 4, color: "pale orange"}] },
    { outerBag: "pale tan", innerBags: [] },
    { outerBag: "light white", innerBags: [{ number: 2, color: "shiny lime"}, { number: 5, color: "dull lavender"}, { number: 4, color: "plaid white"}] },
    { outerBag: "dim beige", innerBags: [{ number: 5, color: "dotted silver"}, { number: 5, color: "dark gold"}, { number: 1, color: "muted turquoise"}, { number: 1, color: "pale olive"}] },
    { outerBag: "muted crimson", innerBags: [{ number: 2, color: "faded silver"}, { number: 2, color: "dark olive"}] },
    { outerBag: "shiny tan", innerBags: [{ number: 2, color: "dotted salmon"}] },
    { outerBag: "dull magenta", innerBags: [{ number: 3, color: "drab black"}, { number: 5, color: "dim purple"}, { number: 3, color: "mirrored bronze"}] },
    { outerBag: "dull white", innerBags: [{ number: 1, color: "clear teal"}, { number: 2, color: "faded violet"}, { number: 4, color: "dull bronze"}, { number: 2, color: "dotted gold"}] },
    { outerBag: "clear green", innerBags: [{ number: 3, color: "pale crimson"}] },
    { outerBag: "dark bronze", innerBags: [{ number: 4, color: "shiny cyan"}, { number: 5, color: "shiny white"}] },
    { outerBag: "vibrant red", innerBags: [{ number: 2, color: "dark tomato"}, { number: 3, color: "muted crimson"}] },
    { outerBag: "striped brown", innerBags: [{ number: 4, color: "pale yellow"}] },
    { outerBag: "light bronze", innerBags: [{ number: 5, color: "drab silver"}, { number: 5, color: "wavy purple"}] },
    { outerBag: "vibrant tomato", innerBags: [{ number: 4, color: "mirrored orange"}, { number: 3, color: "faded teal"}] },
    { outerBag: "bright coral", innerBags: [{ number: 4, color: "clear maroon"}, { number: 3, color: "dim chartreuse"}] },
    { outerBag: "shiny green", innerBags: [{ number: 2, color: "muted crimson"}, { number: 5, color: "pale tan"}, { number: 3, color: "drab black"}, { number: 3, color: "striped teal"}] },
    { outerBag: "mirrored green", innerBags: [{ number: 2, color: "light black"}, { number: 5, color: "posh purple"}, { number: 1, color: "posh tan"}, { number: 1, color: "mirrored orange"}] },
    { outerBag: "dull tan", innerBags: [{ number: 3, color: "bright tomato"}] },
    { outerBag: "muted indigo", innerBags: [{ number: 3, color: "wavy coral"}] },
    { outerBag: "shiny blue", innerBags: [{ number: 1, color: "wavy black"}, { number: 2, color: "dull maroon"}] },
    { outerBag: "posh beige", innerBags: [{ number: 5, color: "dim crimson"}, { number: 1, color: "posh white"}, { number: 2, color: "mirrored teal"}, { number: 2, color: "vibrant chartreuse"}] },
    { outerBag: "dim plum", innerBags: [{ number: 2, color: "vibrant chartreuse"}, { number: 2, color: "posh teal"}, { number: 3, color: "drab white"}] },
    { outerBag: "vibrant teal", innerBags: [{ number: 2, color: "dim tomato"}, { number: 2, color: "dim teal"}, { number: 4, color: "drab chartreuse"}] },
    { outerBag: "wavy olive", innerBags: [{ number: 5, color: "vibrant gold"}, { number: 2, color: "drab black"}, { number: 2, color: "shiny lime"}, { number: 2, color: "light coral"}] },
    { outerBag: "faded white", innerBags: [{ number: 4, color: "posh cyan"}, { number: 1, color: "bright red"}, { number: 2, color: "pale olive"}, { number: 3, color: "plaid olive"}] },
    { outerBag: "pale indigo", innerBags: [{ number: 5, color: "dim crimson"}, { number: 1, color: "dim tan"}, { number: 5, color: "plaid green"}] },
    { outerBag: "pale fuchsia", innerBags: [{ number: 4, color: "light purple"}, { number: 4, color: "clear beige"}, { number: 3, color: "muted teal"}, { number: 3, color: "light blue"}] },
    { outerBag: "faded gray", innerBags: [{ number: 1, color: "clear maroon"}, { number: 2, color: "dim fuchsia"}, { number: 5, color: "bright purple"}, { number: 4, color: "striped turquoise"}] },
    { outerBag: "dark lavender", innerBags: [{ number: 1, color: "muted lavender"}, { number: 2, color: "vibrant crimson"}, { number: 1, color: "clear yellow"}] },
    { outerBag: "light magenta", innerBags: [{ number: 5, color: "faded coral"}, { number: 3, color: "muted green"}, { number: 4, color: "mirrored fuchsia"}, { number: 1, color: "clear coral"}] },
    { outerBag: "plaid cyan", innerBags: [{ number: 1, color: "muted crimson"}] },
    { outerBag: "dim gold", innerBags: [{ number: 3, color: "clear cyan"}, { number: 3, color: "dim tomato"}, { number: 3, color: "shiny lavender"}, { number: 2, color: "vibrant teal"}] },
    { outerBag: "bright tomato", innerBags: [{ number: 1, color: "striped red"}, { number: 1, color: "vibrant violet"}, { number: 4, color: "striped turquoise"}] },
    { outerBag: "drab teal", innerBags: [{ number: 2, color: "posh turquoise"}, { number: 1, color: "shiny black"}] },
    { outerBag: "pale olive", innerBags: [{ number: 2, color: "shiny gold"}, { number: 3, color: "posh bronze"}, { number: 4, color: "bright tomato"}, { number: 2, color: "bright olive"}] },
    { outerBag: "pale brown", innerBags: [{ number: 3, color: "clear tomato"}] },
    { outerBag: "dark yellow", innerBags: [{ number: 3, color: "light brown"}] },
    { outerBag: "pale black", innerBags: [{ number: 4, color: "bright silver"}] },
    { outerBag: "muted brown", innerBags: [{ number: 2, color: "light crimson"}, { number: 4, color: "drab chartreuse"}, { number: 5, color: "pale turquoise"}, { number: 4, color: "posh white"}] },
    { outerBag: "wavy beige", innerBags: [{ number: 2, color: "posh maroon"}, { number: 5, color: "dark turquoise"}] },
    { outerBag: "shiny olive", innerBags: [{ number: 1, color: "light salmon"}, { number: 2, color: "light crimson"}] },
    { outerBag: "dotted teal", innerBags: [{ number: 4, color: "pale turquoise"}] },
    { outerBag: "clear bronze", innerBags: [{ number: 1, color: "dotted tomato"}, { number: 5, color: "striped maroon"}, { number: 5, color: "shiny plum"}, { number: 4, color: "clear lime"}] },
    { outerBag: "dim lime", innerBags: [{ number: 3, color: "dim lavender"}] },
    { outerBag: "shiny aqua", innerBags: [{ number: 2, color: "clear plum"}, { number: 1, color: "plaid lavender"}, { number: 2, color: "faded aqua"}, { number: 1, color: "dim purple"}] },
    { outerBag: "vibrant lime", innerBags: [{ number: 4, color: "dotted plum"}, { number: 2, color: "muted gray"}, { number: 1, color: "posh beige"}] },
    { outerBag: "muted beige", innerBags: [{ number: 1, color: "mirrored lavender"}, { number: 4, color: "muted plum"}] },
    { outerBag: "wavy yellow", innerBags: [{ number: 4, color: "posh cyan"}, { number: 5, color: "dim gold"}, { number: 3, color: "vibrant violet"}] },
    { outerBag: "bright purple", innerBags: [{ number: 1, color: "bright chartreuse"}, { number: 5, color: "posh violet"}, { number: 2, color: "pale purple"}] },
    { outerBag: "vibrant violet", innerBags: [{ number: 2, color: "wavy coral"}, { number: 2, color: "pale gray"}] },
    { outerBag: "faded indigo", innerBags: [{ number: 5, color: "muted tomato"}, { number: 2, color: "dull tomato"}] },
    { outerBag: "mirrored brown", innerBags: [{ number: 1, color: "shiny white"}, { number: 4, color: "dotted lavender"}, { number: 3, color: "striped cyan"}, { number: 5, color: "clear crimson"}] },
    { outerBag: "bright beige", innerBags: [{ number: 2, color: "bright salmon"}] },
    { outerBag: "bright gold", innerBags: [{ number: 4, color: "plaid crimson"}] },
    { outerBag: "drab gold", innerBags: [{ number: 5, color: "pale tan"}] },
    { outerBag: "bright orange", innerBags: [{ number: 1, color: "vibrant gold"}] },
    { outerBag: "shiny brown", innerBags: [{ number: 4, color: "plaid lime"}, { number: 4, color: "dull gray"}, { number: 1, color: "pale tomato"}] },
    { outerBag: "striped beige", innerBags: [{ number: 1, color: "clear yellow"}, { number: 1, color: "pale magenta"}, { number: 4, color: "dull bronze"}, { number: 5, color: "bright fuchsia"}] },
    { outerBag: "clear brown", innerBags: [{ number: 2, color: "bright salmon"}, { number: 2, color: "vibrant turquoise"}] },
    { outerBag: "muted turquoise", innerBags: [{ number: 5, color: "dim crimson"}, { number: 1, color: "drab chartreuse"}] },
    { outerBag: "dark crimson", innerBags: [{ number: 5, color: "bright tomato"}] },
    { outerBag: "clear yellow", innerBags: [{ number: 2, color: "dim olive"}] },
    { outerBag: "bright lime", innerBags: [{ number: 5, color: "faded gray"}, { number: 4, color: "dull gold"}, { number: 3, color: "dark salmon"}, { number: 4, color: "posh lime"}] },
    { outerBag: "muted coral", innerBags: [{ number: 3, color: "posh bronze"}, { number: 3, color: "striped gold"}] },
    { outerBag: "dark salmon", innerBags: [{ number: 2, color: "vibrant indigo"}, { number: 5, color: "posh coral"}, { number: 3, color: "faded silver"}] },
    { outerBag: "vibrant orange", innerBags: [{ number: 4, color: "dark turquoise"}, { number: 2, color: "vibrant lime"}] },
    { outerBag: "pale violet", innerBags: [{ number: 1, color: "shiny brown"}, { number: 2, color: "dim plum"}, { number: 3, color: "dull crimson"}, { number: 3, color: "bright orange"}] },
    { outerBag: "shiny purple", innerBags: [{ number: 1, color: "vibrant lavender"}, { number: 1, color: "dotted yellow"}] },
    { outerBag: "drab orange", innerBags: [{ number: 3, color: "faded aqua"}] },
    { outerBag: "posh brown", innerBags: [{ number: 3, color: "pale magenta"}, { number: 4, color: "faded orange"}, { number: 1, color: "drab chartreuse"}] },
    { outerBag: "shiny bronze", innerBags: [{ number: 3, color: "light magenta"}, { number: 3, color: "drab indigo"}, { number: 5, color: "vibrant yellow"}] },
    { outerBag: "muted teal", innerBags: [{ number: 3, color: "dim olive"}] },
    { outerBag: "bright turquoise", innerBags: [{ number: 3, color: "bright chartreuse"}, { number: 4, color: "mirrored tomato"}] },
    { outerBag: "muted chartreuse", innerBags: [{ number: 4, color: "faded gray"}, { number: 1, color: "dull salmon"}, { number: 3, color: "clear beige"}] },
    { outerBag: "clear white", innerBags: [{ number: 3, color: "muted maroon"}] },
    { outerBag: "posh violet", innerBags: [{ number: 4, color: "shiny white"}, { number: 1, color: "dull orange"}] },
    { outerBag: "dotted brown", innerBags: [{ number: 4, color: "muted aqua"}] },
    { outerBag: "mirrored plum", innerBags: [{ number: 5, color: "clear plum"}, { number: 4, color: "faded tomato"}] },
    { outerBag: "drab crimson", innerBags: [{ number: 1, color: "pale white"}, { number: 4, color: "dotted maroon"}, { number: 2, color: "drab beige"}, { number: 5, color: "drab tan"}] },
    { outerBag: "plaid black", innerBags: [{ number: 1, color: "light salmon"}, { number: 3, color: "mirrored orange"}, { number: 2, color: "dim purple"}] },
    { outerBag: "dim orange", innerBags: [{ number: 4, color: "wavy black"}, { number: 1, color: "clear red"}] },
    { outerBag: "faded plum", innerBags: [{ number: 1, color: "posh violet"}, { number: 1, color: "pale silver"}, { number: 4, color: "muted magenta"}] },
    { outerBag: "vibrant salmon", innerBags: [{ number: 2, color: "dotted red"}, { number: 1, color: "dull maroon"}, { number: 1, color: "plaid tomato"}] },
    { outerBag: "muted cyan", innerBags: [{ number: 5, color: "posh aqua"}, { number: 2, color: "faded silver"}, { number: 2, color: "striped red"}, { number: 4, color: "dim tomato"}] },
    { outerBag: "muted salmon", innerBags: [{ number: 5, color: "muted teal"}, { number: 3, color: "striped cyan"}] },
    { outerBag: "dim cyan", innerBags: [{ number: 5, color: "drab brown"}, { number: 4, color: "muted red"}, { number: 1, color: "wavy coral"}] },
    { outerBag: "drab blue", innerBags: [{ number: 4, color: "faded aqua"}, { number: 2, color: "pale gray"}] },
    { outerBag: "dotted lime", innerBags: [{ number: 3, color: "light olive"}, { number: 2, color: "light tomato"}, { number: 5, color: "dull gold"}, { number: 2, color: "dotted gold"}] },
    { outerBag: "muted violet", innerBags: [{ number: 4, color: "wavy coral"}, { number: 4, color: "pale crimson"}, { number: 1, color: "dim coral"}, { number: 2, color: "mirrored coral"}] },
    { outerBag: "vibrant maroon", innerBags: [{ number: 5, color: "wavy aqua"}, { number: 4, color: "muted orange"}, { number: 3, color: "dull tomato"}] },
    { outerBag: "light tomato", innerBags: [{ number: 3, color: "dim tomato"}, { number: 1, color: "dim purple"}, { number: 2, color: "plaid gray"}, { number: 3, color: "striped red"}] },
    { outerBag: "dotted violet", innerBags: [{ number: 3, color: "muted green"}, { number: 2, color: "faded silver"}] },
    { outerBag: "mirrored coral", innerBags: [{ number: 5, color: "drab black"}, { number: 2, color: "vibrant crimson"}, { number: 2, color: "mirrored gold"}] },
    { outerBag: "muted black", innerBags: [{ number: 3, color: "mirrored plum"}, { number: 2, color: "bright olive"}] },
    { outerBag: "faded olive", innerBags: [{ number: 1, color: "vibrant orange"}, { number: 3, color: "faded gray"}, { number: 3, color: "shiny green"}, { number: 2, color: "muted lavender"}] },
    { outerBag: "clear gold", innerBags: [{ number: 4, color: "dim purple"}] },
    { outerBag: "striped lime", innerBags: [{ number: 2, color: "pale gray"}, { number: 5, color: "light brown"}, { number: 5, color: "vibrant violet"}, { number: 4, color: "bright tomato"}] },
    { outerBag: "drab coral", innerBags: [{ number: 2, color: "pale tan"}, { number: 5, color: "striped teal"}, { number: 1, color: "drab indigo"}] },
    { outerBag: "dotted purple", innerBags: [{ number: 2, color: "faded chartreuse"}, { number: 3, color: "clear beige"}, { number: 4, color: "striped turquoise"}] },
    { outerBag: "light gold", innerBags: [{ number: 2, color: "dark gold"}, { number: 5, color: "striped salmon"}] },
    { outerBag: "faded teal", innerBags: [{ number: 5, color: "plaid black"}, { number: 5, color: "dotted crimson"}, { number: 3, color: "mirrored magenta"}] },
    { outerBag: "dull silver", innerBags: [{ number: 5, color: "bright yellow"}, { number: 4, color: "drab aqua"}, { number: 4, color: "shiny indigo"}] },
    { outerBag: "shiny magenta", innerBags: [{ number: 5, color: "pale purple"}] },
    { outerBag: "dull salmon", innerBags: [{ number: 2, color: "shiny black"}, { number: 1, color: "bright tomato"}] },
    { outerBag: "posh fuchsia", innerBags: [{ number: 1, color: "pale teal"}, { number: 1, color: "clear orange"}] },
    { outerBag: "mirrored lavender", innerBags: [{ number: 2, color: "posh brown"}, { number: 3, color: "light tomato"}, { number: 5, color: "plaid aqua"}, { number: 2, color: "vibrant olive"}] },
    { outerBag: "posh tomato", innerBags: [{ number: 2, color: "drab blue"}] },
    { outerBag: "faded maroon", innerBags: [{ number: 2, color: "dull beige"}, { number: 2, color: "dark gray"}] },
    { outerBag: "dotted tomato", innerBags: [{ number: 4, color: "mirrored olive"}, { number: 4, color: "dull gold"}, { number: 2, color: "dotted silver"}, { number: 4, color: "wavy maroon"}] },
    { outerBag: "muted bronze", innerBags: [{ number: 2, color: "dim olive"}, { number: 2, color: "posh lime"}, { number: 3, color: "drab coral"}, { number: 5, color: "wavy silver"}] },
    { outerBag: "wavy aqua", innerBags: [{ number: 2, color: "striped lime"}, { number: 4, color: "wavy lime"}, { number: 2, color: "dim tan"}, { number: 4, color: "faded cyan"}] },
    { outerBag: "dull violet", innerBags: [{ number: 4, color: "bright gold"}, { number: 2, color: "dim coral"}] },
    { outerBag: "posh gray", innerBags: [{ number: 2, color: "dull bronze"}, { number: 3, color: "faded blue"}, { number: 4, color: "posh silver"}] },
    { outerBag: "striped gold", innerBags: [{ number: 4, color: "wavy lavender"}, { number: 2, color: "muted gray"}, { number: 3, color: "wavy yellow"}] },
    { outerBag: "vibrant black", innerBags: [{ number: 3, color: "shiny silver"}, { number: 1, color: "faded yellow"}] },
    { outerBag: "dull teal", innerBags: [{ number: 4, color: "light blue"}, { number: 3, color: "posh lavender"}] },
    { outerBag: "muted green", innerBags: [{ number: 4, color: "vibrant violet"}] },
    { outerBag: "plaid green", innerBags: [{ number: 3, color: "dim purple"}, { number: 4, color: "dim teal"}, { number: 1, color: "muted cyan"}] },
    { outerBag: "plaid blue", innerBags: [{ number: 2, color: "light purple"}, { number: 4, color: "dim gold"}, { number: 5, color: "pale black"}, { number: 5, color: "dim lavender"}] },
    { outerBag: "vibrant turquoise", innerBags: [{ number: 5, color: "drab orange"}, { number: 4, color: "dark gold"}] },
    { outerBag: "muted plum", innerBags: [{ number: 3, color: "dull aqua"}, { number: 1, color: "wavy lime"}, { number: 3, color: "dark green"}] },
    { outerBag: "bright fuchsia", innerBags: [{ number: 5, color: "wavy gray"}, { number: 1, color: "dim teal"}, { number: 5, color: "muted cyan"}] },
    { outerBag: "clear violet", innerBags: [{ number: 1, color: "bright salmon"}] },
    { outerBag: "dotted chartreuse", innerBags: [{ number: 4, color: "pale plum"}, { number: 2, color: "bright purple"}] },
    { outerBag: "vibrant gray", innerBags: [{ number: 4, color: "dark turquoise"}, { number: 5, color: "faded gold"}, { number: 3, color: "light olive"}] },
    { outerBag: "dark tan", innerBags: [{ number: 2, color: "light olive"}, { number: 1, color: "vibrant fuchsia"}, { number: 4, color: "vibrant blue"}] },
    { outerBag: "mirrored violet", innerBags: [{ number: 2, color: "muted gray"}] },
    { outerBag: "mirrored maroon", innerBags: [{ number: 5, color: "mirrored coral"}, { number: 2, color: "faded lime"}, { number: 3, color: "dark gray"}] },
    { outerBag: "dotted black", innerBags: [{ number: 1, color: "clear violet"}, { number: 2, color: "wavy chartreuse"}, { number: 3, color: "faded silver"}, { number: 2, color: "plaid gray"}] },
    { outerBag: "shiny maroon", innerBags: [{ number: 3, color: "wavy turquoise"}, { number: 2, color: "dim purple"}, { number: 1, color: "shiny silver"}, { number: 2, color: "dim cyan"}] },
    { outerBag: "dull cyan", innerBags: [{ number: 3, color: "mirrored olive"}] },
    { outerBag: "drab brown", innerBags: [{ number: 4, color: "striped lime"}, { number: 2, color: "bright aqua"}] },
    { outerBag: "dim crimson", innerBags: [{ number: 2, color: "drab black"}, { number: 2, color: "vibrant teal"}] },
    { outerBag: "dim brown", innerBags: [{ number: 2, color: "mirrored beige"}] },
    { outerBag: "vibrant silver", innerBags: [{ number: 1, color: "dark gold"}, { number: 4, color: "vibrant indigo"}, { number: 5, color: "dim red"}, { number: 3, color: "light blue"}] },
    { outerBag: "dull olive", innerBags: [{ number: 2, color: "clear red"}, { number: 1, color: "vibrant plum"}] },
    { outerBag: "faded purple", innerBags: [{ number: 5, color: "faded olive"}] },
    { outerBag: "pale yellow", innerBags: [{ number: 3, color: "vibrant teal"}, { number: 3, color: "shiny violet"}, { number: 2, color: "dull yellow"}] },
    { outerBag: "posh black", innerBags: [{ number: 4, color: "clear beige"}, { number: 4, color: "striped salmon"}, { number: 4, color: "wavy lavender"}] },
    { outerBag: "dotted cyan", innerBags: [{ number: 5, color: "shiny crimson"}, { number: 5, color: "dark lavender"}, { number: 5, color: "faded green"}, { number: 3, color: "dull lime"}] },
    { outerBag: "mirrored silver", innerBags: [{ number: 4, color: "light lime"}, { number: 1, color: "posh tomato"}] },
    { outerBag: "pale gold", innerBags: [{ number: 2, color: "striped teal"}, { number: 3, color: "wavy chartreuse"}, { number: 2, color: "plaid tomato"}] },
    { outerBag: "dotted white", innerBags: [{ number: 2, color: "muted purple"}, { number: 2, color: "posh white"}, { number: 3, color: "faded plum"}] },
    { outerBag: "mirrored tan", innerBags: [{ number: 2, color: "clear bronze"}, { number: 2, color: "clear orange"}, { number: 5, color: "striped gray"}] },
    { outerBag: "plaid beige", innerBags: [{ number: 4, color: "drab turquoise"}] },
    { outerBag: "faded red", innerBags: [{ number: 3, color: "vibrant yellow"}, { number: 3, color: "pale brown"}, { number: 4, color: "dim beige"}, { number: 5, color: "wavy chartreuse"}] },
    { outerBag: "pale coral", innerBags: [{ number: 3, color: "clear coral"}] },
    { outerBag: "dull orange", innerBags: [{ number: 5, color: "wavy chartreuse"}, { number: 5, color: "plaid cyan"}] },
    { outerBag: "dull brown", innerBags: [{ number: 5, color: "plaid olive"}, { number: 3, color: "faded chartreuse"}, { number: 3, color: "mirrored crimson"}] },
    { outerBag: "mirrored aqua", innerBags: [{ number: 5, color: "faded green"}] },
    { outerBag: "vibrant tan", innerBags: [{ number: 1, color: "dark turquoise"}, { number: 4, color: "plaid lime"}] },
    { outerBag: "faded fuchsia", innerBags: [{ number: 4, color: "clear gray"}, { number: 4, color: "faded silver"}] },
    { outerBag: "dim purple", innerBags: [{ number: 5, color: "dull lavender"}, { number: 4, color: "faded black"}, { number: 1, color: "muted cyan"}] },
    { outerBag: "posh purple", innerBags: [{ number: 1, color: "wavy turquoise"}, { number: 1, color: "drab cyan"}, { number: 2, color: "dull coral"}, { number: 4, color: "posh yellow"}] },
    { outerBag: "drab turquoise", innerBags: [{ number: 3, color: "dull black"}, { number: 5, color: "dotted bronze"}] },
    { outerBag: "shiny orange", innerBags: [{ number: 5, color: "plaid crimson"}, { number: 4, color: "dotted coral"}] },
    { outerBag: "plaid orange", innerBags: [{ number: 3, color: "wavy gray"}, { number: 5, color: "plaid crimson"}, { number: 2, color: "striped plum"}, { number: 5, color: "pale beige"}] },
    { outerBag: "vibrant bronze", innerBags: [{ number: 1, color: "posh turquoise"}, { number: 3, color: "plaid turquoise"}, { number: 1, color: "dotted crimson"}] },
    { outerBag: "clear tomato", innerBags: [{ number: 5, color: "mirrored fuchsia"}] },
    { outerBag: "wavy coral", innerBags: [{ number: 2, color: "mirrored orange"}] },
    { outerBag: "posh coral", innerBags: [{ number: 5, color: "dotted salmon"}] },
    { outerBag: "bright tan", innerBags: [{ number: 4, color: "drab gray"}, { number: 4, color: "vibrant plum"}] },
    { outerBag: "dotted gray", innerBags: [{ number: 1, color: "dull lime"}, { number: 4, color: "dotted tomato"}, { number: 4, color: "faded gold"}] },
    { outerBag: "pale red", innerBags: [{ number: 2, color: "mirrored olive"}, { number: 1, color: "faded blue"}, { number: 1, color: "dark crimson"}, { number: 3, color: "striped teal"}] },
    { outerBag: "striped aqua", innerBags: [{ number: 2, color: "drab black"}, { number: 5, color: "dull bronze"}, { number: 3, color: "pale purple"}, { number: 4, color: "faded silver"}] },
    { outerBag: "plaid purple", innerBags: [{ number: 3, color: "bright salmon"}, { number: 2, color: "dim beige"}, { number: 3, color: "faded red"}] },
    { outerBag: "drab purple", innerBags: [{ number: 4, color: "dotted black"}, { number: 2, color: "shiny black"}, { number: 1, color: "light plum"}, { number: 1, color: "dotted gold"}] },
    { outerBag: "muted purple", innerBags: [{ number: 3, color: "pale crimson"}] },
    { outerBag: "posh silver", innerBags: [{ number: 4, color: "bright gold"}, { number: 1, color: "dim coral"}, { number: 2, color: "drab chartreuse"}, { number: 1, color: "dim chartreuse"}] },
    { outerBag: "dark black", innerBags: [{ number: 1, color: "bright green"}, { number: 5, color: "plaid cyan"}, { number: 4, color: "dotted purple"}] },
    { outerBag: "striped coral", innerBags: [{ number: 3, color: "shiny lavender"}] },
    { outerBag: "shiny yellow", innerBags: [{ number: 4, color: "dim tomato"}, { number: 1, color: "drab white"}] },
    { outerBag: "bright magenta", innerBags: [{ number: 2, color: "muted silver"}, { number: 3, color: "dull bronze"}, { number: 1, color: "faded blue"}] },
    { outerBag: "light black", innerBags: [{ number: 4, color: "posh silver"}] },
    { outerBag: "pale purple", innerBags: [{ number: 5, color: "dull lavender"}, { number: 1, color: "mirrored orange"}] },
    { outerBag: "striped salmon", innerBags: [{ number: 3, color: "faded chartreuse"}, { number: 2, color: "posh white"}, { number: 1, color: "striped lime"}, { number: 3, color: "drab cyan"}] },
    { outerBag: "dull fuchsia", innerBags: [{ number: 2, color: "plaid tomato"}] },
    { outerBag: "plaid maroon", innerBags: [{ number: 5, color: "dotted red"}, { number: 2, color: "vibrant magenta"}, { number: 4, color: "dotted purple"}] },
    { outerBag: "posh yellow", innerBags: [{ number: 2, color: "wavy beige"}, { number: 5, color: "light yellow"}, { number: 3, color: "striped gray"}] },
    { outerBag: "dull turquoise", innerBags: [{ number: 1, color: "drab lavender"}, { number: 4, color: "faded crimson"}, { number: 2, color: "drab purple"}] },
    { outerBag: "wavy silver", innerBags: [{ number: 5, color: "dotted cyan"}, { number: 2, color: "faded blue"}, { number: 2, color: "faded aqua"}] },
    { outerBag: "clear orange", innerBags: [{ number: 5, color: "posh silver"}, { number: 1, color: "vibrant teal"}, { number: 1, color: "pale tomato"}, { number: 3, color: "dull tomato"}] },
    { outerBag: "drab chartreuse", innerBags: [] },
    { outerBag: "shiny black", innerBags: [{ number: 5, color: "dim teal"}, { number: 1, color: "faded silver"}, { number: 2, color: "posh beige"}, { number: 1, color: "bright olive"}] },
    { outerBag: "pale teal", innerBags: [{ number: 2, color: "dull beige"}] },
    { outerBag: "drab plum", innerBags: [{ number: 5, color: "pale beige"}, { number: 2, color: "wavy maroon"}] },
    { outerBag: "vibrant lavender", innerBags: [{ number: 4, color: "wavy yellow"}] },
    { outerBag: "dim turquoise", innerBags: [{ number: 5, color: "shiny crimson"}] },
    { outerBag: "plaid tan", innerBags: [{ number: 5, color: "clear purple"}, { number: 2, color: "light indigo"}, { number: 4, color: "plaid cyan"}] },
    { outerBag: "pale silver", innerBags: [{ number: 1, color: "pale green"}, { number: 4, color: "striped beige"}] },
    { outerBag: "mirrored bronze", innerBags: [{ number: 1, color: "drab orange"}, { number: 2, color: "posh lavender"}, { number: 2, color: "muted gray"}] },
    { outerBag: "plaid tomato", innerBags: [{ number: 4, color: "striped red"}, { number: 3, color: "bright olive"}] },
    { outerBag: "bright indigo", innerBags: [{ number: 4, color: "dull tan"}] },
    { outerBag: "light violet", innerBags: [{ number: 5, color: "faded magenta"}, { number: 5, color: "drab tomato"}] },
    { outerBag: "clear aqua", innerBags: [{ number: 1, color: "plaid gray"}] },
    { outerBag: "drab salmon", innerBags: [{ number: 5, color: "faded silver"}, { number: 1, color: "bright tomato"}, { number: 1, color: "light lime"}] },
    { outerBag: "light teal", innerBags: [{ number: 5, color: "wavy brown"}, { number: 2, color: "muted indigo"}, { number: 2, color: "pale gold"}] },
    { outerBag: "drab red", innerBags: [{ number: 2, color: "shiny chartreuse"}, { number: 3, color: "dim yellow"}, { number: 3, color: "vibrant teal"}, { number: 3, color: "mirrored silver"}] },
    { outerBag: "bright white", innerBags: [{ number: 5, color: "dotted tan"}, { number: 4, color: "drab beige"}, { number: 3, color: "dim indigo"}, { number: 2, color: "dotted white"}] },
    { outerBag: "dotted fuchsia", innerBags: [{ number: 3, color: "faded tomato"}, { number: 1, color: "dotted lavender"}] },
    { outerBag: "dotted aqua", innerBags: [{ number: 4, color: "clear plum"}, { number: 4, color: "faded maroon"}, { number: 1, color: "posh bronze"}] },
    { outerBag: "light purple", innerBags: [{ number: 5, color: "dotted cyan"}, { number: 4, color: "posh olive"}, { number: 5, color: "plaid fuchsia"}, { number: 3, color: "striped white"}] },
    { outerBag: "shiny indigo", innerBags: [{ number: 2, color: "mirrored gold"}, { number: 4, color: "pale magenta"}, { number: 5, color: "shiny white"}, { number: 4, color: "posh tan"}] },
    { outerBag: "pale turquoise", innerBags: [{ number: 1, color: "pale tan"}, { number: 4, color: "striped red"}, { number: 1, color: "bright olive"}] },
    { outerBag: "plaid aqua", innerBags: [{ number: 3, color: "plaid black"}, { number: 3, color: "dim crimson"}] },
    { outerBag: "posh cyan", innerBags: [{ number: 3, color: "dim tomato"}, { number: 4, color: "pale crimson"}, { number: 4, color: "shiny gold"}] },
    { outerBag: "mirrored white", innerBags: [{ number: 2, color: "faded cyan"}] },
    { outerBag: "shiny chartreuse", innerBags: [{ number: 3, color: "muted maroon"}, { number: 2, color: "dotted teal"}] },
    { outerBag: "dim green", innerBags: [{ number: 4, color: "light salmon"}, { number: 1, color: "muted crimson"}, { number: 2, color: "striped beige"}] },
    { outerBag: "striped blue", innerBags: [{ number: 4, color: "dark bronze"}, { number: 5, color: "faded plum"}, { number: 3, color: "bright white"}] },
    { outerBag: "drab lime", innerBags: [{ number: 4, color: "dull tomato"}] },
    { outerBag: "clear purple", innerBags: [{ number: 2, color: "drab chartreuse"}, { number: 4, color: "clear green"}] },
    { outerBag: "dotted blue", innerBags: [{ number: 5, color: "dim purple"}, { number: 3, color: "dull brown"}] },
    { outerBag: "vibrant cyan", innerBags: [{ number: 2, color: "drab indigo"}, { number: 4, color: "faded chartreuse"}] },
    { outerBag: "light beige", innerBags: [{ number: 3, color: "dark orange"}, { number: 3, color: "vibrant cyan"}] },
    { outerBag: "light lavender", innerBags: [{ number: 1, color: "muted cyan"}, { number: 5, color: "faded tan"}] },
    { outerBag: "dim fuchsia", innerBags: [{ number: 2, color: "pale salmon"}] },
    { outerBag: "mirrored purple", innerBags: [{ number: 2, color: "clear red"}] },
    { outerBag: "faded brown", innerBags: [{ number: 1, color: "clear tan"}, { number: 4, color: "faded crimson"}] },
    { outerBag: "muted magenta", innerBags: [{ number: 5, color: "pale tomato"}, { number: 3, color: "muted maroon"}] },
    { outerBag: "pale beige", innerBags: [{ number: 5, color: "dark gold"}, { number: 1, color: "dull beige"}] },
    { outerBag: "vibrant brown", innerBags: [{ number: 2, color: "striped gold"}, { number: 1, color: "bright gold"}] },
    { outerBag: "clear coral", innerBags: [{ number: 4, color: "pale crimson"}, { number: 1, color: "dark teal"}, { number: 4, color: "mirrored coral"}, { number: 4, color: "striped gold"}] },
    { outerBag: "striped tan", innerBags: [{ number: 4, color: "dim violet"}] },
    { outerBag: "pale chartreuse", innerBags: [{ number: 2, color: "vibrant blue"}, { number: 5, color: "dark turquoise"}, { number: 2, color: "faded olive"}] },
    { outerBag: "posh plum", innerBags: [{ number: 1, color: "plaid aqua"}] },
    { outerBag: "striped purple", innerBags: [{ number: 3, color: "shiny tomato"}, { number: 5, color: "posh purple"}] },
    { outerBag: "dark gold", innerBags: [{ number: 5, color: "vibrant crimson"}, { number: 2, color: "light tomato"}, { number: 3, color: "light salmon"}, { number: 3, color: "muted brown"}] },
    { outerBag: "shiny cyan", innerBags: [{ number: 1, color: "vibrant crimson"}, { number: 5, color: "drab indigo"}] },
    { outerBag: "bright yellow", innerBags: [{ number: 3, color: "plaid indigo"}] },
    { outerBag: "bright blue", innerBags: [{ number: 5, color: "mirrored magenta"}] },
    { outerBag: "dotted salmon", innerBags: [{ number: 5, color: "vibrant crimson"}, { number: 2, color: "posh chartreuse"}, { number: 5, color: "wavy gray"}, { number: 4, color: "pale turquoise"}] },
    { outerBag: "dim olive", innerBags: [{ number: 1, color: "clear cyan"}] },
    { outerBag: "striped turquoise", innerBags: [{ number: 5, color: "faded silver"}, { number: 3, color: "pale tan"}, { number: 5, color: "faded orange"}, { number: 2, color: "bright olive"}] },
    { outerBag: "vibrant beige", innerBags: [{ number: 3, color: "faded yellow"}, { number: 3, color: "bright green"}, { number: 3, color: "faded bronze"}, { number: 4, color: "drab fuchsia"}] },
    { outerBag: "clear maroon", innerBags: [{ number: 1, color: "vibrant indigo"}] },
    { outerBag: "vibrant coral", innerBags: [{ number: 2, color: "mirrored tomato"}, { number: 5, color: "dull bronze"}, { number: 1, color: "vibrant teal"}, { number: 3, color: "pale salmon"}] },
    { outerBag: "dotted orange", innerBags: [{ number: 2, color: "plaid green"}, { number: 4, color: "striped violet"}, { number: 4, color: "bright chartreuse"}, { number: 4, color: "dotted plum"}] },
    { outerBag: "dull tomato", innerBags: [{ number: 2, color: "vibrant crimson"}] },
    { outerBag: "wavy teal", innerBags: [{ number: 1, color: "bright orange"}] },
    { outerBag: "dark teal", innerBags: [{ number: 4, color: "dim tan"}, { number: 4, color: "striped gray"}, { number: 4, color: "dim red"}, { number: 4, color: "plaid bronze"}] },
    { outerBag: "vibrant indigo", innerBags: [{ number: 3, color: "drab coral"}, { number: 2, color: "plaid green"}, { number: 4, color: "shiny gold"}, { number: 3, color: "wavy coral"}] },
    { outerBag: "striped red", innerBags: [{ number: 4, color: "faded silver"}, { number: 4, color: "light salmon"}, { number: 3, color: "drab black"}] },
    { outerBag: "drab aqua", innerBags: [{ number: 5, color: "faded black"}] },
    { outerBag: "wavy plum", innerBags: [{ number: 4, color: "posh blue"}, { number: 5, color: "striped olive"}, { number: 3, color: "shiny violet"}, { number: 4, color: "bright silver"}] },
    { outerBag: "posh lavender", innerBags: [{ number: 3, color: "wavy silver"}, { number: 1, color: "drab lavender"}] },
    { outerBag: "dotted red", innerBags: [{ number: 5, color: "drab bronze"}, { number: 5, color: "plaid gray"}] },
    { outerBag: "dark orange", innerBags: [{ number: 4, color: "mirrored blue"}, { number: 1, color: "drab black"}] },
    { outerBag: "bright lavender", innerBags: [{ number: 4, color: "shiny magenta"}, { number: 2, color: "bright tomato"}, { number: 3, color: "dim salmon"}, { number: 4, color: "dim purple"}] },
    { outerBag: "mirrored chartreuse", innerBags: [{ number: 2, color: "wavy black"}, { number: 4, color: "dull cyan"}, { number: 5, color: "striped coral"}] },
    { outerBag: "mirrored tomato", innerBags: [{ number: 5, color: "clear beige"}] },
    { outerBag: "wavy fuchsia", innerBags: [{ number: 2, color: "muted silver"}, { number: 2, color: "shiny gold"}] },
    { outerBag: "muted lime", innerBags: [{ number: 2, color: "striped turquoise"}, { number: 3, color: "dim tan"}] },
    { outerBag: "shiny white", innerBags: [{ number: 4, color: "mirrored olive"}] },
    { outerBag: "posh maroon", innerBags: [{ number: 3, color: "vibrant violet"}, { number: 5, color: "striped turquoise"}, { number: 2, color: "dull lavender"}, { number: 4, color: "faded orange"}] },
    { outerBag: "faded aqua", innerBags: [{ number: 2, color: "faded orange"}, { number: 2, color: "pale magenta"}, { number: 1, color: "posh white"}] },
    { outerBag: "mirrored blue", innerBags: [{ number: 5, color: "pale purple"}, { number: 2, color: "light red"}, { number: 2, color: "striped teal"}, { number: 4, color: "shiny crimson"}] },
    { outerBag: "dotted plum", innerBags: [{ number: 1, color: "light chartreuse"}, { number: 5, color: "drab tan"}, { number: 3, color: "pale red"}] },
    { outerBag: "muted tan", innerBags: [{ number: 3, color: "drab cyan"}, { number: 2, color: "posh olive"}, { number: 1, color: "dim tomato"}] },
    { outerBag: "shiny tomato", innerBags: [{ number: 3, color: "mirrored cyan"}, { number: 5, color: "dim yellow"}] },
    { outerBag: "pale lavender", innerBags: [{ number: 2, color: "dull beige"}] },
    { outerBag: "pale orange", innerBags: [{ number: 1, color: "posh gold"}] },
    { outerBag: "wavy green", innerBags: [{ number: 4, color: "posh bronze"}] },
    { outerBag: "faded lavender", innerBags: [{ number: 3, color: "clear gold"}, { number: 4, color: "mirrored cyan"}, { number: 4, color: "faded silver"}, { number: 5, color: "posh chartreuse"}] },
    { outerBag: "posh teal", innerBags: [{ number: 1, color: "shiny purple"}, { number: 4, color: "dotted violet"}, { number: 1, color: "dotted tomato"}, { number: 5, color: "dull indigo"}] },
    { outerBag: "clear crimson", innerBags: [{ number: 2, color: "shiny lavender"}] },
    { outerBag: "dim black", innerBags: [{ number: 2, color: "vibrant coral"}, { number: 2, color: "drab green"}] },
    { outerBag: "dull crimson", innerBags: [{ number: 3, color: "vibrant orange"}, { number: 2, color: "drab salmon"}] },
    { outerBag: "muted gold", innerBags: [{ number: 3, color: "posh chartreuse"}, { number: 4, color: "striped gold"}, { number: 4, color: "drab brown"}, { number: 2, color: "dim black"}] },
    { outerBag: "dull chartreuse", innerBags: [{ number: 3, color: "clear fuchsia"}] },
    { outerBag: "light orange", innerBags: [{ number: 5, color: "clear orange"}, { number: 5, color: "faded bronze"}, { number: 3, color: "clear crimson"}] },
    { outerBag: "dark tomato", innerBags: [{ number: 5, color: "dotted chartreuse"}, { number: 3, color: "dull gray"}, { number: 5, color: "muted crimson"}] },
    { outerBag: "dark brown", innerBags: [{ number: 3, color: "posh red"}] },
    { outerBag: "faded green", innerBags: [{ number: 1, color: "dark white"}] },
    { outerBag: "dark olive", innerBags: [{ number: 4, color: "vibrant teal"}, { number: 3, color: "pale magenta"}, { number: 4, color: "pale gray"}] },
    { outerBag: "striped bronze", innerBags: [{ number: 3, color: "striped tan"}, { number: 5, color: "dark gray"}, { number: 4, color: "vibrant white"}] },
    { outerBag: "striped black", innerBags: [{ number: 1, color: "striped turquoise"}, { number: 1, color: "vibrant olive"}, { number: 1, color: "striped salmon"}] },
    { outerBag: "clear plum", innerBags: [{ number: 4, color: "wavy chartreuse"}, { number: 1, color: "pale bronze"}, { number: 2, color: "striped plum"}] },
    { outerBag: "faded tan", innerBags: [{ number: 2, color: "muted cyan"}, { number: 4, color: "dim salmon"}, { number: 3, color: "vibrant crimson"}, { number: 4, color: "striped plum"}] },
    { outerBag: "faded silver", innerBags: [] },
    { outerBag: "light silver", innerBags: [{ number: 4, color: "muted gray"}, { number: 3, color: "mirrored crimson"}, { number: 3, color: "dull tan"}, { number: 2, color: "drab indigo"}] },
    { outerBag: "dim aqua", innerBags: [{ number: 2, color: "posh tomato"}, { number: 2, color: "muted coral"}, { number: 5, color: "wavy gray"}, { number: 3, color: "dull tan"}] },
    { outerBag: "vibrant crimson", innerBags: [{ number: 1, color: "shiny lavender"}, { number: 3, color: "bright tomato"}] },
    { outerBag: "dim maroon", innerBags: [{ number: 4, color: "light olive"}] },
    { outerBag: "bright maroon", innerBags: [{ number: 2, color: "faded tan"}, { number: 5, color: "pale tomato"}, { number: 5, color: "dotted purple"}] },
    { outerBag: "dim gray", innerBags: [{ number: 1, color: "muted gold"}, { number: 4, color: "shiny magenta"}, { number: 2, color: "wavy salmon"}, { number: 2, color: "posh violet"}] },
    { outerBag: "dim coral", innerBags: [{ number: 3, color: "striped coral"}, { number: 5, color: "clear gold"}, { number: 3, color: "wavy chartreuse"}] },
    { outerBag: "posh indigo", innerBags: [{ number: 3, color: "dull salmon"}] },
    { outerBag: "striped green", innerBags: [{ number: 3, color: "vibrant crimson"}, { number: 4, color: "plaid plum"}, { number: 4, color: "muted brown"}] },
    { outerBag: "dull purple", innerBags: [{ number: 3, color: "drab gold"}, { number: 1, color: "plaid gray"}, { number: 4, color: "striped silver"}] },
    { outerBag: "light yellow", innerBags: [{ number: 3, color: "pale salmon"}, { number: 5, color: "dark cyan"}, { number: 3, color: "dull tomato"}, { number: 3, color: "mirrored silver"}] },
    { outerBag: "shiny red", innerBags: [{ number: 3, color: "faded gold"}, { number: 1, color: "light salmon"}, { number: 5, color: "mirrored turquoise"}] },
    { outerBag: "vibrant magenta", innerBags: [{ number: 1, color: "drab tomato"}, { number: 5, color: "plaid cyan"}] },
    { outerBag: "plaid lavender", innerBags: [{ number: 1, color: "dull lavender"}, { number: 5, color: "vibrant black"}, { number: 2, color: "muted olive"}, { number: 4, color: "shiny lavender"}] },
    { outerBag: "light cyan", innerBags: [{ number: 1, color: "bright silver"}] },
    { outerBag: "dark plum", innerBags: [{ number: 2, color: "drab salmon"}, { number: 3, color: "dull violet"}, { number: 3, color: "posh lime"}] },
    { outerBag: "dull green", innerBags: [{ number: 4, color: "bright gold"}, { number: 2, color: "posh gold"}, { number: 2, color: "striped plum"}] },
    { outerBag: "wavy salmon", innerBags: [{ number: 3, color: "faded gray"}, { number: 5, color: "dotted cyan"}, { number: 3, color: "plaid maroon"}] },
    { outerBag: "pale lime", innerBags: [{ number: 1, color: "shiny purple"}] },
    { outerBag: "shiny plum", innerBags: [{ number: 3, color: "mirrored magenta"}, { number: 4, color: "clear violet"}, { number: 5, color: "dull tomato"}, { number: 5, color: "dotted violet"}] },
    { outerBag: "dim red", innerBags: [{ number: 2, color: "posh white"}, { number: 4, color: "drab cyan"}, { number: 1, color: "dark yellow"}, { number: 1, color: "pale purple"}] },
    { outerBag: "light red", innerBags: [{ number: 3, color: "dotted indigo"}, { number: 4, color: "bright tomato"}, { number: 1, color: "mirrored olive"}, { number: 4, color: "pale turquoise"}] },
    { outerBag: "dim yellow", innerBags: [{ number: 5, color: "faded aqua"}, { number: 2, color: "shiny purple"}, { number: 1, color: "plaid bronze"}] },
    { outerBag: "drab magenta", innerBags: [{ number: 4, color: "dotted coral"}, { number: 3, color: "plaid lime"}] },
    { outerBag: "clear gray", innerBags: [{ number: 5, color: "plaid green"}, { number: 3, color: "pale purple"}] },
    { outerBag: "plaid turquoise", innerBags: [{ number: 4, color: "mirrored crimson"}, { number: 2, color: "muted lavender"}, { number: 3, color: "light blue"}, { number: 2, color: "dull blue"}] },
    { outerBag: "mirrored turquoise", innerBags: [{ number: 5, color: "muted magenta"}, { number: 4, color: "light red"}] },
    { outerBag: "pale plum", innerBags: [{ number: 3, color: "clear beige"}, { number: 5, color: "striped plum"}, { number: 4, color: "striped lime"}, { number: 2, color: "striped teal"}] },
    { outerBag: "vibrant chartreuse", innerBags: [{ number: 2, color: "drab chartreuse"}, { number: 2, color: "striped red"}, { number: 4, color: "dim teal"}] },
    { outerBag: "striped gray", innerBags: [{ number: 3, color: "striped red"}, { number: 1, color: "drab green"}] },
    { outerBag: "muted maroon", innerBags: [{ number: 4, color: "clear yellow"}, { number: 1, color: "dim tan"}, { number: 3, color: "vibrant cyan"}, { number: 1, color: "bright tomato"}] },
    { outerBag: "posh aqua", innerBags: [{ number: 3, color: "faded silver"}, { number: 5, color: "pale tan"}, { number: 2, color: "striped red"}, { number: 3, color: "light salmon"}] },
    { outerBag: "dotted bronze", innerBags: [{ number: 4, color: "striped gold"}, { number: 5, color: "dark lime"}, { number: 2, color: "pale magenta"}, { number: 1, color: "pale salmon"}] },
    { outerBag: "dark aqua", innerBags: [{ number: 4, color: "dull salmon"}, { number: 2, color: "striped salmon"}, { number: 5, color: "clear turquoise"}] },
    { outerBag: "plaid brown", innerBags: [{ number: 4, color: "posh silver"}] },
    { outerBag: "bright cyan", innerBags: [{ number: 2, color: "posh yellow"}, { number: 5, color: "posh lavender"}, { number: 4, color: "shiny cyan"}] },
    { outerBag: "dark indigo", innerBags: [{ number: 5, color: "pale turquoise"}, { number: 4, color: "light crimson"}, { number: 2, color: "dim orange"}] },
    { outerBag: "muted yellow", innerBags: [{ number: 3, color: "light coral"}, { number: 1, color: "vibrant turquoise"}, { number: 5, color: "clear magenta"}, { number: 2, color: "pale olive"}] },
    { outerBag: "clear fuchsia", innerBags: [{ number: 2, color: "posh silver"}, { number: 1, color: "striped yellow"}, { number: 3, color: "striped lime"}] },
    { outerBag: "bright salmon", innerBags: [{ number: 2, color: "vibrant cyan"}] },
    { outerBag: "dotted maroon", innerBags: [{ number: 2, color: "posh violet"}] },
    { outerBag: "shiny violet", innerBags: [{ number: 3, color: "dim teal"}] },
    { outerBag: "plaid teal", innerBags: [{ number: 2, color: "drab orange"}, { number: 1, color: "dim violet"}, { number: 1, color: "bright fuchsia"}] },
    { outerBag: "faded salmon", innerBags: [{ number: 5, color: "drab orange"}, { number: 3, color: "clear indigo"}, { number: 1, color: "plaid cyan"}] },
    { outerBag: "shiny beige", innerBags: [{ number: 5, color: "bright brown"}, { number: 4, color: "pale brown"}] },
    { outerBag: "plaid yellow", innerBags: [{ number: 3, color: "vibrant crimson"}] },
    { outerBag: "light indigo", innerBags: [{ number: 4, color: "vibrant cyan"}, { number: 2, color: "dotted purple"}] },
    { outerBag: "dull aqua", innerBags: [{ number: 5, color: "pale tan"}] },
    { outerBag: "posh green", innerBags: [{ number: 2, color: "light silver"}, { number: 3, color: "posh lime"}, { number: 2, color: "vibrant olive"}] },
    { outerBag: "dark beige", innerBags: [{ number: 3, color: "dotted coral"}, { number: 5, color: "wavy chartreuse"}] },
    { outerBag: "mirrored salmon", innerBags: [{ number: 4, color: "posh blue"}, { number: 5, color: "posh yellow"}, { number: 4, color: "posh fuchsia"}, { number: 3, color: "drab tomato"}] },
    { outerBag: "pale crimson", innerBags: [{ number: 3, color: "dim tomato"}, { number: 3, color: "vibrant teal"}, { number: 5, color: "dotted silver"}] },
    { outerBag: "wavy gray", innerBags: [{ number: 1, color: "dim olive"}, { number: 4, color: "plaid green"}] },
    { outerBag: "bright olive", innerBags: [{ number: 5, color: "faded orange"}, { number: 1, color: "plaid black"}, { number: 2, color: "plaid gray"}, { number: 3, color: "faded silver"}] },
    { outerBag: "light lime", innerBags: [{ number: 5, color: "dull lavender"}, { number: 2, color: "posh aqua"}, { number: 4, color: "dull aqua"}] },
    { outerBag: "dim salmon", innerBags: [{ number: 3, color: "muted lavender"}, { number: 1, color: "light lime"}] },
    { outerBag: "dark white", innerBags: [{ number: 1, color: "posh aqua"}, { number: 3, color: "wavy black"}] },
    { outerBag: "posh magenta", innerBags: [{ number: 5, color: "striped silver"}, { number: 3, color: "wavy bronze"}, { number: 3, color: "faded beige"}] },
    { outerBag: "mirrored cyan", innerBags: [{ number: 5, color: "light brown"}, { number: 1, color: "muted cyan"}, { number: 4, color: "posh silver"}] },
    { outerBag: "dark magenta", innerBags: [{ number: 2, color: "muted indigo"}, { number: 2, color: "muted coral"}] },
    { outerBag: "clear salmon", innerBags: [{ number: 3, color: "pale chartreuse"}] },
    { outerBag: "dim tan", innerBags: [{ number: 2, color: "pale crimson"}] },
    { outerBag: "bright gray", innerBags: [{ number: 3, color: "mirrored fuchsia"}] },
    { outerBag: "bright green", innerBags: [{ number: 5, color: "plaid crimson"}, { number: 3, color: "striped turquoise"}] },
    { outerBag: "faded black", innerBags: [{ number: 1, color: "striped red"}, { number: 1, color: "dim teal"}, { number: 5, color: "faded silver"}, { number: 3, color: "striped plum"}] },
    { outerBag: "wavy orange", innerBags: [{ number: 1, color: "dark white"}] },
    { outerBag: "wavy cyan", innerBags: [{ number: 5, color: "light olive"}] },
    { outerBag: "muted blue", innerBags: [{ number: 5, color: "wavy maroon"}, { number: 1, color: "light tomato"}] },
    { outerBag: "light green", innerBags: [{ number: 1, color: "shiny teal"}, { number: 5, color: "bright lime"}, { number: 4, color: "drab white"}, { number: 5, color: "posh aqua"}] },
    { outerBag: "drab white", innerBags: [{ number: 4, color: "posh silver"}, { number: 4, color: "mirrored crimson"}] },
    { outerBag: "bright teal", innerBags: [{ number: 5, color: "dotted purple"}, { number: 1, color: "faded yellow"}, { number: 4, color: "shiny coral"}] },
    { outerBag: "light plum", innerBags: [{ number: 3, color: "pale cyan"}, { number: 5, color: "faded tan"}] },
    { outerBag: "faded coral", innerBags: [{ number: 4, color: "dull gray"}] },
    { outerBag: "dotted coral", innerBags: [{ number: 2, color: "posh bronze"}, { number: 5, color: "posh aqua"}, { number: 2, color: "mirrored violet"}] },
    { outerBag: "pale cyan", innerBags: [{ number: 2, color: "mirrored orange"}, { number: 2, color: "dim tomato"}] },
    { outerBag: "drab beige", innerBags: [{ number: 4, color: "bright aqua"}, { number: 2, color: "mirrored tomato"}, { number: 2, color: "plaid turquoise"}, { number: 1, color: "wavy chartreuse"}] },
    { outerBag: "dark maroon", innerBags: [{ number: 1, color: "dull gray"}, { number: 2, color: "mirrored olive"}, { number: 1, color: "light olive"}, { number: 1, color: "shiny fuchsia"}] },
    { outerBag: "wavy white", innerBags: [{ number: 4, color: "dull lavender"}] },
    { outerBag: "dull gray", innerBags: [{ number: 5, color: "plaid black"}, { number: 3, color: "light lime"}, { number: 2, color: "wavy chartreuse"}, { number: 5, color: "dim tomato"}] },
    { outerBag: "clear red", innerBags: [{ number: 5, color: "light crimson"}, { number: 3, color: "faded chartreuse"}, { number: 4, color: "clear teal"}, { number: 4, color: "mirrored blue"}] },
    { outerBag: "bright bronze", innerBags: [{ number: 1, color: "clear magenta"}, { number: 2, color: "clear gray"}, { number: 2, color: "dull coral"}, { number: 5, color: "vibrant gray"}] }]